config/routes.rb
Rails.application.routes.draw do

root 'home#index'
resources :quotes
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :quotes
  validates :name, presence: true, uniqueness: true

  def self.quotes_by_theme(theme)
    self.where(name: theme).joins(:quotes).first
  end
end

app/models/film.rb
class Film < ActiveRecord::Base
  has_many :quotes, as: :medium
end

app/models/literature.rb
class Literature < ActiveRecord::Base
  has_many :quotes, as: :medium
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  has_and_belongs_to_many :categories
  belongs_to :medium, polymorphic: true
  validates :content, :attribution, presence: true

  scope :random, -> { order('RANDOM()').first }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @quote_of_day = Quote.find(Time.now.day.to_i)
    @categories = Category.all
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index
    @random_quote = scope.random
    render layout: false
  end

  private
  def scope
    if params[:category_id]
      Category.find(params[:category_id]).quotes
    else
      Quote
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/home/_category.html.erb
<%= link_to category.name, quotes_url(category_id: category.id), class: 'getquote' %>

app/views/home/index.html.erb
<header class="hero">
  <div class="container">
    <div class="row">
      <div class="col-md-12 col-xs-12">
        <h1 class="center-block">Quote Generator</h1>
      </div>
    </div>
  </div>
</header>


<section class="quotes">
  <div class="container">
    <div class="row">
      <div class="col-md-12 col-xs-12">
				<blockquote id="output">
					<%= render @quote_of_day %>
				</blockquote>
			</div>
		</div>
	</div>
</section>
<%= render partial: 'category', collection: @categories %>
<%= link_to "Random", quotes_url, class: 'getquote' %>
<%= link_to "Origin", root_url, id: 'go_home' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QuotesGenerator</title>
  <link href='http://fonts.googleapis.com/css?family=Parisienne' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Caudex:700|Parisienne&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/quotes/_quote.html.erb
<p><%= quote.content %></p>
<footer>
	<cite><%= quote.medium.title if quote.medium %></cite>
	<span class="attribution"><%= quote.attribution %></span>
</footer>

app/views/quotes/index.html.erb
<%= render @random_quote %>